module.exports = {
	pages:{
		student:{
			entry:"./src/pages/student/main.js",
			template:"./public/index.html",
			filename:"student.html"
		},
		manager:{
			entry:"./src/pages/manager/main.js",
			template:"./public/index.html",
			filename:"manager.html"
		},
		teacher:{
			entry:"./src/pages/teacher/main.js",
			template:"./public/index.html",
			filename:"teacher.html"
		},
		login:{
			entry:"./src/pages/login/main.js",
			template:"./public/index.html",
			filename:"login.html"
		},
	}
}